<?php
/** @var $this SchumacherFM_Sesame_Block_Adminhtml_Token */
$baseJsUrl = $this->getSesameJsBaseUrl();
?>

<script async="true" type="text/javascript" src="<?php echo $baseJsUrl; ?>qrcodejs/qrcode.min.js"></script>
<script async="true" type="text/javascript" src="<?php echo $baseJsUrl; ?>sesame.js"></script>

<a href="#" id="sesameLogin" data-params='<?php echo $this->getLoginParamJson(); ?>'>
    <?php echo Mage::helper('sesame')->__('Secure login via QR-Code'); ?>
</a>
